<?php

namespace App\Services\Takedown;

use App\Models\AuditLog;
use App\Models\DefensiveAction;
use App\Models\IncidentChecklist;
use App\Models\User;
use Exception;

class DefensiveActionService
{
    /**
     * Generate rule payload text based on rule type and target.
     */
    public function generateRulePayload(string $ruleType, string $targetType, string $targetValue, ?string $description = null): string
    {
        $comment = "# Generated by WebGuard Defensive Engine - " . now()->format('Y-m-d H:i') . " WIB";
        $descComment = $description ? "# Alasan: {$description}" : "# Target terindikasi aktivitas berbahaya";

        return match ($ruleType) {
            'FIREWALL_RULE' => $this->generateFirewallRules($targetValue, $comment, $descComment),
            'WAF_RULE' => $this->generateWafRules($targetValue, $comment, $descComment),
            'DNS_SINKHOLE' => $this->generateDnsSinkholeRules($targetValue, $comment, $descComment),
            'INTERNAL_BLOCKLIST' => $this->generateBlocklistRules($targetValue, $comment),
            'IOC_LIST' => $this->generateIocPayload($targetType, $targetValue, $description),
            'EMAIL_FILTER' => $this->generateEmailFilterRules($targetValue, $comment),
            'PROXY_BLOCK' => $this->generateProxyBlockRules($targetValue, $comment),
            'SIEM_RULE' => $this->generateSiemSigmaRule($targetType, $targetValue, $description),
            default => "# Custom Internal Policy\nACTION: BLOCK\nTARGET: {$targetValue}\nSCOPE: Internal Network Only\n",
        };
    }

    /**
     * Generate standard firewall templates (iptables, UFW, pfSense, MikroTik).
     */
    protected function generateFirewallRules(string $target, string $comment, string $descComment): string
    {
        return <<<EOT
{$comment}
{$descComment}
# Scope: INTERNAL INFRASTRUCTURE ONLY

# --- 1. Linux UFW (Uncomplicated Firewall) ---
sudo ufw deny out to {$target} comment 'WebGuard: Block Outbound to Malicious Host'

# --- 2. Linux iptables (Outbound & Inbound Drop) ---
iptables -A OUTPUT -d {$target} -j DROP -m comment --comment "WebGuard Block"
iptables -A FORWARD -d {$target} -j DROP

# --- 3. pfSense / OPNsense EasyRule syntax ---
# Action: Block, Interface: WAN/LAN, Direction: out, Destination: {$target}

# --- 4. MikroTik RouterOS CLI ---
/ip firewall filter add chain=forward dst-address={$target} action=drop comment="WebGuard Malicious Host Drop"
EOT;
    }

    /**
     * Generate WAF rules (ModSecurity, Nginx map, Cloudflare Custom Rule).
     */
    protected function generateWafRules(string $target, string $comment, string $descComment): string
    {
        return <<<EOT
{$comment}
{$descComment}

# --- 1. ModSecurity v3 / OWASP CRS Rule ---
SecRule REQUEST_HEADERS:Host "@streq {$target}" \
    "id:1900101,phase:1,deny,status:403,log,msg:'WebGuard: Akses ke domain terblokir dihentikan'"

# --- 2. Nginx Reverse Proxy / Map Block ---
# Letakkan di file /etc/nginx/conf.d/blocked_domains.conf:
# map \$http_host \$blocked_domain {
#     default 0;
#     "{$target}" 1;
# }
# if (\$blocked_domain) { return 403 "Blocked by WebGuard Defense Policy"; }

# --- 3. Cloudflare WAF Custom Rule (Expression) ---
(http.host eq "{$target}") or (http.referer contains "{$target}") -> Block
EOT;
    }

    /**
     * Generate DNS Sinkhole configs (BIND RPZ, Pi-hole, Unbound).
     */
    protected function generateDnsSinkholeRules(string $target, string $comment, string $descComment): string
    {
        return <<<EOT
{$comment}
{$descComment}

# --- 1. BIND 9 Response Policy Zone (RPZ) ---
{$target} CNAME .
*.{$target} CNAME .
# Dialihkan ke internal sinkhole warning IP (127.0.0.1 atau internal captive portal):
# {$target} A 192.168.1.254

# --- 2. Pi-hole / dnsmasq regex or blacklist ---
address=/{$target}/0.0.0.0

# --- 3. Unbound Local Zone ---
local-zone: "{$target}" static
local-data: "{$target} A 0.0.0.0"
local-data: "{$target} AAAA ::"
EOT;
    }

    /**
     * Generate internal Hosts/Blocklist.
     */
    protected function generateBlocklistRules(string $target, string $comment): string
    {
        return <<<EOT
{$comment}
# Format /etc/hosts internal:
0.0.0.0 {$target}
0.0.0.0 www.{$target}
::1 {$target}
EOT;
    }

    /**
     * Generate Email filter rules (Postfix, SpamAssassin).
     */
    protected function generateEmailFilterRules(string $target, string $comment): string
    {
        return <<<EOT
{$comment}
# --- 1. Postfix /etc/postfix/sender_access ---
{$target} REJECT WebGuard Policy: Domain teridentifikasi dalam kampanye phishing/hoax

# --- 2. SpamAssassin Rule (/etc/mail/spamassassin/local.cf) ---
header WEBGARD_PHISH_HOST From =~ /{$target}/i
score WEBGARD_PHISH_HOST 10.0
describe WEBGARD_PHISH_HOST Domain pengirim terdaftar dalam WebGuard IOC List
EOT;
    }

    /**
     * Generate Proxy block rules (Squid).
     */
    protected function generateProxyBlockRules(string $target, string $comment): string
    {
        return <<<EOT
{$comment}
# Squid Proxy (/etc/squid/squid.conf)
acl webguard_malicious dstdomain .{$target}
http_access deny webguard_malicious
deny_info ERR_ACCESS_DENIED webguard_malicious
EOT;
    }

    /**
     * Generate SIEM Sigma detection rule in YAML format.
     */
    protected function generateSiemSigmaRule(string $targetType, string $targetValue, ?string $desc): string
    {
        $id = \Illuminate\Support\Str::uuid();
        return <<<EOT
title: WebGuard Internal Detection - Suspicious {$targetType} {$targetValue}
id: {$id}
status: experimental
description: Mendeteksi koneksi jaringan keluar atau query DNS internal menuju target berbahaya ({$targetValue})
references:
    - https://webguard.id/defensive
author: WebGuard Incident Response Team
date: 2026/09/23
logsource:
    category: dns
    product: zeek/windows-sysmon
detection:
    selection:
        query: '*{$targetValue}*'
    condition: selection
falsepositives:
    - Verifikasi oleh tim SecOps
level: high
tags:
    - attack.initial_access
    - attack.command_and_control
EOT;
    }

    /**
     * Generate STIX 2.1 IOC JSON.
     */
    protected function generateIocPayload(string $targetType, string $targetValue, ?string $desc): string
    {
        $now = now()->toISOString();
        return json_encode([
            'type' => 'indicator',
            'spec_version' => '2.1',
            'id' => 'indicator--' . \Illuminate\Support\Str::uuid(),
            'created' => $now,
            'modified' => $now,
            'name' => "WebGuard Indicator for {$targetValue}",
            'description' => $desc ?: 'Indikator terdeteksi melalui passive investigation WebGuard',
            'pattern_type' => 'stix',
            'pattern' => match ($targetType) {
                'IP' => "[ipv4-addr:value = '{$targetValue}']",
                'DOMAIN' => "[domain-name:value = '{$targetValue}']",
                'URL' => "[url:value = '{$targetValue}']",
                default => "[domain-name:value = '{$targetValue}']",
            },
            'valid_from' => $now,
        ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }

    /**
     * Attach standard Incident Response Checklist items to a defensive action / case.
     */
    public function attachDefaultChecklist(DefensiveAction $action): void
    {
        $steps = [
            // Fase 1: Identifikasi
            ['step' => 1, 'phase' => 'IDENTIFICATION', 'name' => 'Validasi Bukti Forensik', 'instr' => 'Verifikasi hash SHA-256 pada laporan dan kecocokan tangkapan layar bukti.'],
            ['step' => 2, 'phase' => 'IDENTIFICATION', 'name' => 'Konfirmasi Domain & IP Server', 'instr' => 'Pastikan target bukan merupakan aset resmi internal atau domain whitelist kedinasan.'],
            // Fase 2: Kontainmen (Containment)
            ['step' => 3, 'phase' => 'CONTAINMENT', 'name' => 'Sinkhole DNS Internal', 'instr' => 'Terapkan RPZ / sinkhole pada resolver DNS internal agar pengguna lokal tidak terpapar.'],
            ['step' => 4, 'phase' => 'CONTAINMENT', 'name' => 'Terapkan Aturan Firewall Perimeter', 'instr' => 'Terapkan rule blokir koneksi keluar pada gateway firewall dinas.'],
            // Fase 3: Eradikasi & Pelaporan
            ['step' => 5, 'phase' => 'ERADICATION', 'name' => 'Pengajuan Laporan Takedown Resmi', 'instr' => 'Kirim paket bukti resmi ke provider hosting / registrar / Kominfo Aduan Konten.'],
            ['step' => 6, 'phase' => 'ERADICATION', 'name' => 'Monitor SLA & Catat Nomor Tiket', 'instr' => 'Input nomor tiket provider ke dalam sistem WebGuard untuk pemantauan tindak lanjut.'],
            // Fase 4: Pemulihan & Pembelajaran
            ['step' => 7, 'phase' => 'RECOVERY', 'name' => 'Verifikasi Penurunan Situs (Status Down)', 'instr' => 'Uji secara pasif apakah website target telah ditangguhkan (404/suspended/null).'],
            ['step' => 8, 'phase' => 'LESSONS_LEARNED', 'name' => 'Dokumentasi & Penutupan Kasus', 'instr' => 'Arsipkan catatan akhir dan evaluasi efektivitas respons untuk audit dinas.'],
        ];

        foreach ($steps as $s) {
            IncidentChecklist::create([
                'takedown_case_id' => $action->takedown_case_id,
                'defensive_action_id' => $action->id,
                'step_number' => $s['step'],
                'phase' => $s['phase'],
                'task_name' => $s['name'],
                'instructions' => $s['instr'],
                'is_completed' => false,
            ]);
        }
    }

    /**
     * RBAC Approval: Admin or Super Admin review.
     */
    public function reviewAction(DefensiveAction $action, User $reviewer): DefensiveAction
    {
        $action->update([
            'status' => 'PENDING_APPROVAL',
            'reviewed_by' => $reviewer->id,
        ]);

        AuditLog::log('DEFENSIVE_ACTION_REVIEWED', 'DefensiveAction', (string) $action->id, [
            'action_code' => $action->action_code,
            'reviewer' => $reviewer->name,
        ]);

        return $action;
    }

    /**
     * RBAC Approval: Super Admin approve.
     */
    public function approveAction(DefensiveAction $action, User $approver): DefensiveAction
    {
        $action->update([
            'status' => 'APPROVED',
            'approved_by' => $approver->id,
            'approved_at' => now(),
        ]);

        AuditLog::log('DEFENSIVE_ACTION_APPROVED', 'DefensiveAction', (string) $action->id, [
            'action_code' => $action->action_code,
            'approver' => $approver->name,
        ]);

        return $action;
    }

    /**
     * Mark rule deployed internally by network administrator.
     */
    public function markDeployed(DefensiveAction $action, User $admin): DefensiveAction
    {
        $action->update([
            'status' => 'DEPLOYED_INTERNALLY',
            'deployed_at' => now(),
            'verified_at' => now(),
        ]);

        AuditLog::log('DEFENSIVE_ACTION_DEPLOYED', 'DefensiveAction', (string) $action->id, [
            'action_code' => $action->action_code,
            'deployed_by' => $admin->name,
        ]);

        return $action;
    }
}
